import os

DATABASE_SCHEMA_NAME = os.environ['DATABASE_SCHEMA_NAME']
ESDL_UPDATER_QUEUE_URL = os.environ['ESDL_UPDATER_QUEUE_URL']
CONTAINER_TIMEOUT = os.environ['CONTAINER_TIMEOUT']
ETM_QUEUE_URL = os.environ['ETM_QUEUE_URL']
FLASK_CWD = os.environ['FLASK_CWD']
ENVIRONMENT = os.environ['ENVIRONMENT']
BUCKET_NAME = os.environ['BUCKET_NAME']
